### ISSUE TITLE
Action fails with "invalid value workflow reference: references to workflows must be rooted in '.github/workflows'"

### ISSUE THREAD

**Issue by bryan-lw** [jesalg/commit-hawk-action#61]
I created /.github/workflows/commit-hawk.yaml with the contents:
```
name: "commit-hawk"
on:
  push:
    branches:
      - master
    paths:
      - '**/Jenkinsfile'
jobs:
  commit-hawk:
    uses: actions/commit-hawk-action@v1
    with:
      slack_webhook_url: 'https://hooks.slack.com/services/<stuff>/<morestuff>/<yetmorestuff>'
      slack_message: 'Contents of config file(s) were changed'

```

and when it tries to run, it fails with the error:

```Error : .github#L1
invalid value workflow reference: references to workflows must be rooted in '.github/workflows'
```

What am I doing wrong?  I haven't been able to find any reference to this error and have tried various combinations of paths.
